### ISSUE TITLE
Cannot find module '@manekinekko/angular-web-bluetooth'

### ISSUE THREAD

**Issue by Stan92** [manekinekko/angular-web-bluetooth#66]
Hi,

I follow the instruction for installing the package, but I get this error
Cannot find module '@manekinekko/angular-web-bluetooth'
As well the package @types/web-bluetooth is missing
I use npm 6.14.4 and angular 9.1 (ubuntu)

EDIT: 
Just tried with Windows 10/Angular 8.3.26 (same errors).

**Comment by manekinekko** [comment]
Hi, would you mind using the issue template so we can have more details on how to reproduce this issue?

**Comment by manekinekko** [comment]
FYI, both packages are available on NPM...
![image](https://user-images.githubusercontent.com/1699357/79542961-e7be3300-808c-11ea-9486-4d08532a412c.png)

**Comment by Stan92** [comment]
Ok, I'll use the template... FYI, it worked with v7.0.0

**Comment by Stan92** [comment]
**Describe the bug**
The module can't be found using the command
import  { BluetoothCore } from '@manekinekko/angular-web-bluetooth'

Even if I get the right version (9.1.0) using the command
npm info @manekinekko/angular-web-bluetooth version

**To Reproduce**

npm i -S @manekinekko/angular-web-bluetooth @types/web-bluetooth

Within a component I add
import { WebBluetoothModule } from '@manekinekko/angular-web-bluetooth';

Running ng s, I get this error

```
ERROR in src/app/app.component.ts:2:31 - error TS2307: Cannot find module '@manekinekko/angular-web-bluetooth'.

import { BluetoothCore } from '@manekinekko/angular-web-bluetooth';
src/app/app.module.ts:6:36 - error TS2307: Cannot find module '@manekinekko/angular-web-bluetooth'.


```


**Desktop (please complete the following information):**
 - OS: Windows 10 & Ubuntu 18.04
 - Angular 8 & 9

**Comment by vpalaciopbcs** [comment]
I have the same issue,  just starting a new project and try to import the library to replicate the problem. I checked out the sample code and there works fine but I also see the folder structure is a little different and also you have the PATH property in tsconfig.json of the example. 
Tested with angular 9

**Comment by drdreinhard** [comment]
Same to me. Angular 9

**Comment by the-bug** [comment]
After migrating a project from 7.0.0 to 9.1.0 this issues is happening there at well...

**Comment by Anavra** [comment]
Running the bluetooth starter directly from a clone of this repo seems to work fine, but I get this issue when adding it to my own project. 

```
error TS2307: Cannot find module '@manekinekko/angular-web-bluetooth'.
11 import { BluetoothCore } from '@manekinekko/angular-web-bluetooth';
```

@types/web-bluetooth is functioning correctly as the type definitions can be used with no problem.

**Comment by developersnively** [comment]
Hi, same problem for me. Angular 9.1.0 on Mac Catalina 10.15.4

**Comment by stephen-dirtcreative** [comment]
Same problem using yarn add with 9.1.0. Looking at the installed folder, it seems like the library code prior to build is being provided rather than the distribution ready code. Listing the directory at `node_modules/@maneikinekko/angular-web-bluetooth` gives:
```
.release-it.json
README.md
karma.conf.js
ng-package.json
package.json
src/
tsconfig.lib.json
tsconfig.spec.json
tslint.json
```

**Comment by Express85** [comment]
I bump into the same issue. Is there already a solution to this problem?

**Comment by stephen-dirtcreative** [comment]
@Express85 I worked around the problem by cloning the Git repository, then manually adding the build output as a library to my project.

**Comment by ankiitbansal** [comment]
same issue for me as well. using node version 14.4.
Tried installing, ununistalling the npm package, getting some different errors.

Any workaround please?

also @stephen-dirtcreative  can you please share the build output that you are mentioning with some steps. 

![image](https://user-images.githubusercontent.com/13376808/84602835-bfde2680-aea7-11ea-8456-68e51d854203.png)

**Comment by stephen-dirtcreative** [comment]
@ankiitbansal Sure, or at least I'll try.

What I did:
1. Clone the repo: git clone https://github.com/manekinekko/angular-web-bluetooth.git
1. `npm install` and `npm audit` -- The 2 high severity vulnerabilities were fixable, at least on my platform, `npm audit fix` picked off 7 of 10 low vulnerabilities, also. I didn't attempt to address the remaining low vulnerabilities as they had to do with karma, protractor, and angular-build
1. `npm run prebuild` -- This is the script in package.json for building the library project, it should output to `[repo root]/dist/manekinekko/angular-web-bluetooth`
1. Copy the `manekinekko` folder that was created under `[repo root]/dist` to your Angular project's `dist` folder.
1. Edit your tsconfig.json to include a section similar to the following:
```jsonc
{
  // ... skipping unrelated option settings ...
  "paths": {
    "angular-web-bluetooth": [
      "dist/manekinekko/angular-web-bluetooth/manekinekko-angular-web-bluetooth",
      "dist/manekinekko/angular-web-bluetooth"
    ]
  }
}
```
Don't forget it's a JSON file, so no trailing commas, and quotes matter. Also, just to be over-cautious: the '... skipping unrelated options settings ...' is NOT something to put in the file!

With the folder imported to your `dist/` and configured in `tsconfig.json`, you _should_ be able to import from `'angular-web-bluetooth'. For example, in `src/app/app.module.ts` I have:
```typescript
import { WebBluetoothModule } from 'angular-web-bluetooth'
```

Make sure you have @types/web-bluetooth installed via your package manager. Hopefully, I didn't miss anything. Even more hopefully the next version bump of the package will resolve the issue either intentionally or just as a side-effect, and this won't be something anyone needs to rely on.

**Comment by rjstalb** [comment]
Ultimately the issue is with using Ivy in Angular 9. I've found a work around running `npm run prebuild` with Ivy off, and then turning it back on for my local project (where I want to use Ivy)...

in tsconfig.json, add:

` "angularCompilerOptions": {
    "enableIvy": false
  }`

See [Angular docs](https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9) for reference

**Comment by manekinekko** [comment]
The issue has been fixed. Please try the new version [v9.1.1](https://github.com/manekinekko/angular-web-bluetooth/releases/tag/v9.1.1).

**Comment by ankiitbansal** [comment]
Thanks. Will give it a try.

Thanks and Regards,
Ankit Bansal

**Comment by rjstalb** [comment]
@manekinekko thanks! confirming this works. appreciate the responsiveness here :)

**Comment by manekinekko** [comment]
Thank you @rjstalb
